config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  resources :tasks
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create]
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :status, presence: true, length: {maximum: 10}
  validates :content, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  before_save{ self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: true }
  
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      redirect_to root_url
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id]=@user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_logged_in
  before_action :self_find, only: [:show,:edit,:update,:destroy]
  
  def index
    if logged_in?
      @tasks = current_user.tasks.order("created_at DESC")
    end
  end
  
  def show
  end
  
  def new
    @task=Task.new
  end
  
  def create
    @task=current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_url
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      redirect_to root_url
    else
      render :edit
    end
  end
  
  def destroy
    if @task
      @task.destroy
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  private
  
  def self_find
    @task=current_user.tasks.find_by(id: params[:id])
    
    # @task = current_user.tasks.find_by(id: params[:id])
    # if (@task == nil)
    #   redirect_to root_url
    # end
  end
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show]
  
  def index
    
  end
  
  def show
    @user = User.find_by(id: params[:id])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li><%= link_to  '新規タスク作成', new_task_path %></li>
          <li><%= link_to "プロフィール", user_path(@current_user) %></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <%= form_for(@task) do |f| %>
      <% if task.errors.any? %>
        <div id="alert alert-warning">
          <ul>
           <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
           <% end %>
          </ul>
        </div>
        
      <% end %>
      
      <div class="form-group">
        <%= f.label :status, "ステータス" %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, "タスク" %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <%= f.submit "作成", class: 'btn btn-primary' %>
      
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
  
  <li>
    <%= link_to task.id, task %>
     .
    <%= task.status %>
     :
    <%= task.content %>
  </li>
  
  <% end %>
  
</ul>

<%= link_to "新規タスク作成", new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<p>
  <%= @task.status %>
</p>

<p>
  <%= @task.content %>
</p>

<%= link_to "一覧へ", tasks_path %>
<br>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<br>
<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除してよろしいですか？"} %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.text_field :password_confirmation, class: "form-control" %>
    </div>
    <div class>
      <%= f.label :password, "Password" %>
      <%= f.text_field :password, class: "form-control" %>
    </div>
    <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-3 text-right">
    <h1><%= @user.name %></h1>
  </div>
  <div class="col-md-3">
    <%= link_to root_path do %>
      タスク一覧<span class="badge"><%= @count_tasks %></span>
    <% end %>
  </div>
</div>